name: Build and Publish

on:
  pull_request:
    branches:
    - main
    types:
    - closed

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: print env variable
      run: echo ${{ vars.API_URL }}
