name: Build and Publish

on:
  pull_request:
    branches:
    - main
    types:
    - closed

environment: prod

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: print env variable
      run: echo ${{ vars.API_URL }}
  setup2:
    runs-on: ubuntu-latest
    steps:
    - name: print env variable in setup2
      run: echo ${{ vars.API_URL }}

