name: Test action

on:
  pull_request:
    branches:
    - dev
    types:
    - opened
    - synchronize
    - closed

jobs:
  setup_env:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create .env file
      env:
        HOST_ENV: HOST_${{ vars.ENV_NAME }}
      run: |
        echo $HOST_ENV
        echo ${{ secrets[$HOST_ENV] }}"