name: Build and Publish

on:
  push:
    branches:
    - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Tag
      run: |
        echo "IMAGE_TAG=${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') && github.event.ref || git rev-parse --short $GITHUB_SHA }}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image to GitHub Container Registry
      run: |
        docker tag $REGISTRY/$IMAGE_NAME:$IMAGE_TAG $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          docker pull $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          docker run -d --name $WEB_APP_NAME -p $WEB_APP_PORT:$WEB_APP_PORT $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

