name: Test action

on:
  pull_request:
    branches:
    - dev
    types:
    - opened
    - synchronize
    - closed

jobs:
  test:
    runs-on: ubuntu-latest
    uses: uses: axelvazq/action_test/.github/workflows/setup-env.yml@feature/pr
    with:
      environment: DEV